services:
  - type: web
    name: doccypher-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m backend.download_models
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: FASTEMBED_CACHE_PATH
        value: /opt/render/project/src/.fastembed_cache